const NUM_HEALING_POTS = 2;
const SIZE_HEALING_POTS = 70;
const KEY_ATTACK = "A";
const KEY_HEAL = "H";
const MAX_LIFE = 100;
const MIN_LIFE = 0;
const MAX_DAMAGE_ATTACK = 20;
const MIN_DAMAGE_ATTACK = 10;
const MAX_MONSTERS = 3;
const MIN_MONSTERS = 1;

export {NUM_HEALING_POTS,SIZE_HEALING_POTS,KEY_ATTACK,KEY_HEAL,MAX_LIFE,MIN_LIFE,MAX_DAMAGE_ATTACK,MIN_DAMAGE_ATTACK,MAX_MONSTERS,MIN_MONSTERS};
